w10d01/silicon-valley/config/routes.rb
Rails.application.routes.draw do
  resources :visitors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :characters

  resources :quotes
end

w10d01/silicon-valley/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

w10d01/silicon-valley/app/models/character.rb
class Character < ApplicationRecord
  has_many :quotes # character.quotes
end

w10d01/silicon-valley/app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :character # quote.character
end

w10d01/silicon-valley/app/models/visitor.rb
class Visitor < ApplicationRecord
end

w10d01/silicon-valley/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/silicon-valley/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
    # render 'index'
  end
end

w10d01/silicon-valley/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
    @character = Character.find 2

    render json: {
      quotes: @quotes,
      more_stuff: 'hello world',
      character: @character
    }
  end
end

w10d01/silicon-valley/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: %i[ show edit update destroy ]

  # GET /visitors or /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_path, status: :see_other, notice: "Visitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.fetch(:visitor, {})
    end
end

w10d01/silicon-valley/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/silicon-valley/app/helpers/characters_helper.rb
module CharactersHelper
end

w10d01/silicon-valley/app/helpers/quotes_helper.rb
module QuotesHelper
end

w10d01/silicon-valley/app/helpers/visitors_helper.rb
module VisitorsHelper
end

w10d01/silicon-valley/app/views/characters/index.html.erb
<h1>All the Characters</h1>

<% @characters.each do |character| %>
  <div class="character">
    <h2>Name: <%= character.name %></h2>
    <h2>Company: <%= character.company %></h2>
  </div>
<% end %>

w10d01/silicon-valley/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiliconValley</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/silicon-valley/app/views/quotes/_quote.html.erb
<div class="quote">
  <h2>Quote: <%= quote.quote %></h2>
  <h2>Url: <%= quote.url %></h2>
  <h2>Character: <%= quote.character.name %></h2>
</div>

w10d01/silicon-valley/app/views/quotes/index.html.erb
<h1>All the quotes!</h1>

<a href="/characters">Characters</a>
<%= link_to "Characters", "/characters" %>
<%= link_to "Characters", characters_path %>

<%= render @quotes %>

w10d01/silicon-valley/app/views/visitors/_form.html.erb
<%= form_with(model: visitor) do |form| %>
  <% if visitor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

w10d01/silicon-valley/app/views/visitors/_visitor.html.erb
<div id="<%= dom_id visitor %>">
</div>

w10d01/silicon-valley/app/views/visitors/edit.html.erb
<h1>Editing visitor</h1>

<%= render "form", visitor: @visitor %>

<br>

<div>
  <%= link_to "Show this visitor", @visitor %> |
  <%= link_to "Back to visitors", visitors_path %>
</div>

w10d01/silicon-valley/app/views/visitors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Visitors</h1>

<div id="visitors">
  <% @visitors.each do |visitor| %>
    <%= render visitor %>
    <p>
      <%= link_to "Show this visitor", visitor %>
    </p>
  <% end %>
</div>

<%= link_to "New visitor", new_visitor_path %>

w10d01/silicon-valley/app/views/visitors/new.html.erb
<h1>New visitor</h1>

<%= render "form", visitor: @visitor %>

<br>

<div>
  <%= link_to "Back to visitors", visitors_path %>
</div>

w10d01/silicon-valley/app/views/visitors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visitor %>

<div>
  <%= link_to "Edit this visitor", edit_visitor_path(@visitor) %> |
  <%= link_to "Back to visitors", visitors_path %>

  <%= button_to "Destroy this visitor", @visitor, method: :delete %>
</div>